In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt 

In [2]:
words = open('/kaggle/input/datasets/sydulhasantawsif/names-makemore/names.txt', 'r').read().splitlines()

In [3]:
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [4]:
chars = sorted(list(set(''.join(words))))

In [5]:
stoi = {s:i+1 for i, s in enumerate(chars)}    
stoi['.'] = 0
itos = {i:s for s, i in stoi.items()}

In [6]:
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [7]:
block_size = 3
X, Y = [], []

for w in words[:5]:
    print(w)
    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '--->', itos[ix])
        context = context[1:] + [ix] 

X = torch.tensor(X)
Y = torch.tensor(Y)

emma
... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .
olivia
... ---> o
..o ---> l
.ol ---> i
oli ---> v
liv ---> i
ivi ---> a
via ---> .
ava
... ---> a
..a ---> v
.av ---> a
ava ---> .
isabella
... ---> i
..i ---> s
.is ---> a
isa ---> b
sab ---> e
abe ---> l
bel ---> l
ell ---> a
lla ---> .
sophia
... ---> s
..s ---> o
.so ---> p
sop ---> h
oph ---> i
phi ---> a
hia ---> .


In [8]:
X.shape, Y.shape

(torch.Size([32, 3]), torch.Size([32]))

In [9]:
X

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22],
        [ 9, 22,  9],
        [22,  9,  1],
        [ 0,  0,  0],
        [ 0,  0,  1],
        [ 0,  1, 22],
        [ 1, 22,  1],
        [ 0,  0,  0],
        [ 0,  0,  9],
        [ 0,  9, 19],
        [ 9, 19,  1],
        [19,  1,  2],
        [ 1,  2,  5],
        [ 2,  5, 12],
        [ 5, 12, 12],
        [12, 12,  1],
        [ 0,  0,  0],
        [ 0,  0, 19],
        [ 0, 19, 15],
        [19, 15, 16],
        [15, 16,  8],
        [16,  8,  9],
        [ 8,  9,  1]])

In [10]:
C = torch.randn((27, 2))
C

tensor([[ 4.9180e-01, -3.7771e-01],
        [-3.3152e-01, -1.8079e+00],
        [-1.1430e-01,  5.7341e-01],
        [-3.4632e-01, -7.9365e-01],
        [ 1.4861e-01, -6.8827e-01],
        [ 1.3588e+00,  1.9425e-01],
        [-4.2244e-01,  2.4508e+00],
        [ 1.0372e+00,  4.9789e-01],
        [-4.9883e-01,  1.6334e+00],
        [-6.5768e-01, -6.6390e-01],
        [ 5.5412e-01, -2.7766e-01],
        [-1.0161e+00, -2.3316e-01],
        [ 4.4279e-01,  9.3593e-01],
        [ 3.1164e-01,  2.3983e+00],
        [ 1.5838e-01, -1.3622e+00],
        [-1.3238e-02, -5.8314e-01],
        [ 1.5036e+00,  6.2759e-01],
        [-2.0948e-01,  3.5743e-01],
        [-9.1371e-01, -9.6676e-01],
        [ 4.9199e-01,  2.2302e-01],
        [-1.4170e-01,  2.2551e-01],
        [ 7.3384e-01,  5.1405e-01],
        [-1.4691e+00, -9.3397e-01],
        [ 1.8939e-03,  6.7919e-01],
        [-1.1912e+00,  1.1356e+00],
        [ 6.1336e-01,  3.6065e-01],
        [ 4.1112e-01,  7.9531e-01]])

In [11]:
C[X].shape

torch.Size([32, 3, 2])

In [12]:
emb = C[X]

In [13]:
emb

tensor([[[ 0.4918, -0.3777],
         [ 0.4918, -0.3777],
         [ 0.4918, -0.3777]],

        [[ 0.4918, -0.3777],
         [ 0.4918, -0.3777],
         [ 1.3588,  0.1942]],

        [[ 0.4918, -0.3777],
         [ 1.3588,  0.1942],
         [ 0.3116,  2.3983]],

        [[ 1.3588,  0.1942],
         [ 0.3116,  2.3983],
         [ 0.3116,  2.3983]],

        [[ 0.3116,  2.3983],
         [ 0.3116,  2.3983],
         [-0.3315, -1.8079]],

        [[ 0.4918, -0.3777],
         [ 0.4918, -0.3777],
         [ 0.4918, -0.3777]],

        [[ 0.4918, -0.3777],
         [ 0.4918, -0.3777],
         [-0.0132, -0.5831]],

        [[ 0.4918, -0.3777],
         [-0.0132, -0.5831],
         [ 0.4428,  0.9359]],

        [[-0.0132, -0.5831],
         [ 0.4428,  0.9359],
         [-0.6577, -0.6639]],

        [[ 0.4428,  0.9359],
         [-0.6577, -0.6639],
         [-1.4691, -0.9340]],

        [[-0.6577, -0.6639],
         [-1.4691, -0.9340],
         [-0.6577, -0.6639]],

        [[-1.4691, -0

In [14]:
w1 = torch.randn((6, 100))
b1 = torch.randn(100)

In [15]:
emb.view(32, 6) #torch.cat(torch.unbind(emb, 1), 1).shape

tensor([[ 0.4918, -0.3777,  0.4918, -0.3777,  0.4918, -0.3777],
        [ 0.4918, -0.3777,  0.4918, -0.3777,  1.3588,  0.1942],
        [ 0.4918, -0.3777,  1.3588,  0.1942,  0.3116,  2.3983],
        [ 1.3588,  0.1942,  0.3116,  2.3983,  0.3116,  2.3983],
        [ 0.3116,  2.3983,  0.3116,  2.3983, -0.3315, -1.8079],
        [ 0.4918, -0.3777,  0.4918, -0.3777,  0.4918, -0.3777],
        [ 0.4918, -0.3777,  0.4918, -0.3777, -0.0132, -0.5831],
        [ 0.4918, -0.3777, -0.0132, -0.5831,  0.4428,  0.9359],
        [-0.0132, -0.5831,  0.4428,  0.9359, -0.6577, -0.6639],
        [ 0.4428,  0.9359, -0.6577, -0.6639, -1.4691, -0.9340],
        [-0.6577, -0.6639, -1.4691, -0.9340, -0.6577, -0.6639],
        [-1.4691, -0.9340, -0.6577, -0.6639, -0.3315, -1.8079],
        [ 0.4918, -0.3777,  0.4918, -0.3777,  0.4918, -0.3777],
        [ 0.4918, -0.3777,  0.4918, -0.3777, -0.3315, -1.8079],
        [ 0.4918, -0.3777, -0.3315, -1.8079, -1.4691, -0.9340],
        [-0.3315, -1.8079, -1.4691, -0.9

In [16]:
h = torch.tanh(emb.view(32, 6) @ w1 + b1)

In [17]:
h.shape

torch.Size([32, 100])

In [18]:
w2 = torch.randn((100, 27))
b2 = torch.randn(27)

In [19]:
logits = h @ w2 + b2
logits.shape

torch.Size([32, 27])

In [20]:
counts = logits.exp()

In [21]:
prob = counts / counts.sum(1, keepdims = True)

In [22]:
prob.shape

torch.Size([32, 27])

In [23]:
prob[torch.arange(32), Y]

tensor([4.4928e-07, 2.6416e-11, 8.9004e-01, 1.6827e-05, 1.6675e-06, 5.5844e-08,
        1.7105e-03, 1.3208e-11, 3.3921e-12, 2.7280e-07, 3.2011e-11, 1.1914e-02,
        4.9936e-10, 5.7999e-05, 6.6900e-09, 2.5658e-04, 9.2055e-08, 2.4649e-02,
        6.5062e-09, 8.7120e-01, 6.3282e-05, 2.0357e-13, 3.4701e-08, 1.0576e-06,
        4.2980e-06, 1.5752e-06, 6.7792e-07, 1.2565e-05, 2.3721e-15, 1.4410e-12,
        1.4044e-09, 2.7475e-04])